services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgresql
    network_mode: bridge
  web:
    build:
      context: .
      dockerfile: Dockerfile-webui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./Docker/config.json:/root/passwordmanager-ui/config.json
    network_mode: bridge
  server:
    build:
      context: .
      dockerfile: Dockerfile-server
    restart: always
    ports:
      - "50000:50000"
    volumes:
      - ./Docker/config.json:/opt/passwordmanager/config.json
    network_mode: bridge