FROM alpine

# install node
RUN apk add nodejs npm
# set working directory
WORKDIR /root/passwordmanager-ui
# copy project file
COPY ./Password-LostPassword/package.json .
# install node packages
RUN npm set progress=false && \
    npm config set depth 0 && \
    npm install --only=production && \
    npm cache verify
# copy app files
COPY ./Password-LostPassword/config.json .
COPY ./Password-LostPassword/src ./src
COPY ./Password-LostPassword/views ./views
# application server port
EXPOSE 3000
# default run command
CMD [ "npm", "start" ]