#
# Build stage
#
FROM maven:3.6.3-openjdk-15-slim AS build
COPY ./PasswordManager/src /home/app/src
COPY ./PasswordManager/resources /home/app/resources
COPY ./PasswordManager/pom-deployment.xml /home/app/pom.xml
RUN mvn -f /home/app/pom.xml clean package

#
# Package stage
#
FROM openjdk:15-jdk-slim
COPY --from=build /home/app/target/PasswordManager-0.4.9-SNAPSHOT-jar-with-dependencies.jar /opt/passwordmanager/passwordmanager.jar
COPY --from=build /home/app/target/config.json /opt/passwordmanager/config.json
EXPOSE 50000
ENTRYPOINT ["java","-jar","/opt/passwordmanager/passwordmanager.jar", "--config", "/opt/passwordmanager/config.json"]
