# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Docker build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build PasswordManager server with Docker
      run: docker build . -t passwordmanager_server:latest --file Dockerfile-server
    - name: Build Node.js web UI with Docker
      run: docker build . -t passwordmanager_webui:latest --file Dockerfile-webui
    - name: Build PostgreSQL with Docker
      run: docker build . -t passwordmanager_postgres:latest --file Dockerfile-postgres
      
