# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: PasswordManager CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build with Maven
      run: mvn -B clean build --file PasswordManager/pom.xml
    - name: Package jar with Maven
      run: mvn -B clean package --file PasswordManager/pom-deployment.xml
    - name: Package exe on Windows
      if: matrix.os == 'windows-latest'
      run: mvn -B clean package --file PasswordManager/pom-deploy-client.xml
